// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lite/VideoTaskShow.proto

package com.yy.lite.brpc.service;

public final class VideoTaskShow {
  private VideoTaskShow() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoTaskShowReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yy.lite.brpc.service.VideoTaskShowReq)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.yy.lite.brpc.service.VideoTaskShowReq}
   */
  public  static final class VideoTaskShowReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yy.lite.brpc.service.VideoTaskShowReq)
      VideoTaskShowReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VideoTaskShowReq.newBuilder() to construct.
    private VideoTaskShowReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoTaskShowReq() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VideoTaskShowReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.class, com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.Builder.class);
    }

    /**
     * Protobuf enum {@code com.yy.lite.brpc.service.VideoTaskShowReq.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>none = 0;</code>
       */
      none(0),
      /**
       * <code>max = 7134;</code>
       */
      max(7134),
      /**
       * <code>min = 1041;</code>
       */
      min(1041),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>none = 0;</code>
       */
      public static final int none_VALUE = 0;
      /**
       * <code>max = 7134;</code>
       */
      public static final int max_VALUE = 7134;
      /**
       * <code>min = 1041;</code>
       */
      public static final int min_VALUE = 1041;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return none;
          case 7134: return max;
          case 1041: return min;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.yy.lite.brpc.service.VideoTaskShowReq.Type)
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq)) {
        return super.equals(obj);
      }
      com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq other = (com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yy.lite.brpc.service.VideoTaskShowReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yy.lite.brpc.service.VideoTaskShowReq)
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.class, com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.Builder.class);
      }

      // Construct using com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_descriptor;
      }

      public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq getDefaultInstanceForType() {
        return com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.getDefaultInstance();
      }

      public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq build() {
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq buildPartial() {
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq result = new com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq) {
          return mergeFrom((com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq other) {
        if (other == com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yy.lite.brpc.service.VideoTaskShowReq)
    }

    // @@protoc_insertion_point(class_scope:com.yy.lite.brpc.service.VideoTaskShowReq)
    private static final com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq();
    }

    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoTaskShowReq>
        PARSER = new com.google.protobuf.AbstractParser<VideoTaskShowReq>() {
      public VideoTaskShowReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VideoTaskShowReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VideoTaskShowReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VideoTaskShowReq> getParserForType() {
      return PARSER;
    }

    public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VideoTaskShowRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yy.lite.brpc.service.VideoTaskShowResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否展示 0：不展示 1：展示入口
     * </pre>
     *
     * <code>int32 show = 1;</code>
     */
    int getShow();

    /**
     * <pre>
     *跳转链接
     * </pre>
     *
     * <code>string skipUrl = 2;</code>
     */
    String getSkipUrl();
    /**
     * <pre>
     *跳转链接
     * </pre>
     *
     * <code>string skipUrl = 2;</code>
     */
    com.google.protobuf.ByteString
        getSkipUrlBytes();
  }
  /**
   * Protobuf type {@code com.yy.lite.brpc.service.VideoTaskShowResp}
   */
  public  static final class VideoTaskShowResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yy.lite.brpc.service.VideoTaskShowResp)
      VideoTaskShowRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VideoTaskShowResp.newBuilder() to construct.
    private VideoTaskShowResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoTaskShowResp() {
      show_ = 0;
      skipUrl_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VideoTaskShowResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              show_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              skipUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.class, com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.Builder.class);
    }

    /**
     * Protobuf enum {@code com.yy.lite.brpc.service.VideoTaskShowResp.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>none = 0;</code>
       */
      none(0),
      /**
       * <code>max = 7134;</code>
       */
      max(7134),
      /**
       * <code>min = 1042;</code>
       */
      min(1042),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>none = 0;</code>
       */
      public static final int none_VALUE = 0;
      /**
       * <code>max = 7134;</code>
       */
      public static final int max_VALUE = 7134;
      /**
       * <code>min = 1042;</code>
       */
      public static final int min_VALUE = 1042;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return none;
          case 7134: return max;
          case 1042: return min;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.yy.lite.brpc.service.VideoTaskShowResp.Type)
    }

    public static final int SHOW_FIELD_NUMBER = 1;
    private int show_;
    /**
     * <pre>
     *是否展示 0：不展示 1：展示入口
     * </pre>
     *
     * <code>int32 show = 1;</code>
     */
    public int getShow() {
      return show_;
    }

    public static final int SKIPURL_FIELD_NUMBER = 2;
    private volatile Object skipUrl_;
    /**
     * <pre>
     *跳转链接
     * </pre>
     *
     * <code>string skipUrl = 2;</code>
     */
    public String getSkipUrl() {
      Object ref = skipUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        skipUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *跳转链接
     * </pre>
     *
     * <code>string skipUrl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSkipUrlBytes() {
      Object ref = skipUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        skipUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (show_ != 0) {
        output.writeInt32(1, show_);
      }
      if (!getSkipUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, skipUrl_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (show_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, show_);
      }
      if (!getSkipUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, skipUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp)) {
        return super.equals(obj);
      }
      com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp other = (com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp) obj;

      boolean result = true;
      result = result && (getShow()
          == other.getShow());
      result = result && getSkipUrl()
          .equals(other.getSkipUrl());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SHOW_FIELD_NUMBER;
      hash = (53 * hash) + getShow();
      hash = (37 * hash) + SKIPURL_FIELD_NUMBER;
      hash = (53 * hash) + getSkipUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yy.lite.brpc.service.VideoTaskShowResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yy.lite.brpc.service.VideoTaskShowResp)
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.class, com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.Builder.class);
      }

      // Construct using com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        show_ = 0;

        skipUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yy.lite.brpc.service.VideoTaskShow.internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_descriptor;
      }

      public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp getDefaultInstanceForType() {
        return com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.getDefaultInstance();
      }

      public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp build() {
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp buildPartial() {
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp result = new com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp(this);
        result.show_ = show_;
        result.skipUrl_ = skipUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp) {
          return mergeFrom((com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp other) {
        if (other == com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp.getDefaultInstance()) return this;
        if (other.getShow() != 0) {
          setShow(other.getShow());
        }
        if (!other.getSkipUrl().isEmpty()) {
          skipUrl_ = other.skipUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int show_ ;
      /**
       * <pre>
       *是否展示 0：不展示 1：展示入口
       * </pre>
       *
       * <code>int32 show = 1;</code>
       */
      public int getShow() {
        return show_;
      }
      /**
       * <pre>
       *是否展示 0：不展示 1：展示入口
       * </pre>
       *
       * <code>int32 show = 1;</code>
       */
      public Builder setShow(int value) {
        
        show_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否展示 0：不展示 1：展示入口
       * </pre>
       *
       * <code>int32 show = 1;</code>
       */
      public Builder clearShow() {
        
        show_ = 0;
        onChanged();
        return this;
      }

      private Object skipUrl_ = "";
      /**
       * <pre>
       *跳转链接
       * </pre>
       *
       * <code>string skipUrl = 2;</code>
       */
      public String getSkipUrl() {
        Object ref = skipUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          skipUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *跳转链接
       * </pre>
       *
       * <code>string skipUrl = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSkipUrlBytes() {
        Object ref = skipUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          skipUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *跳转链接
       * </pre>
       *
       * <code>string skipUrl = 2;</code>
       */
      public Builder setSkipUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skipUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *跳转链接
       * </pre>
       *
       * <code>string skipUrl = 2;</code>
       */
      public Builder clearSkipUrl() {
        
        skipUrl_ = getDefaultInstance().getSkipUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *跳转链接
       * </pre>
       *
       * <code>string skipUrl = 2;</code>
       */
      public Builder setSkipUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skipUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yy.lite.brpc.service.VideoTaskShowResp)
    }

    // @@protoc_insertion_point(class_scope:com.yy.lite.brpc.service.VideoTaskShowResp)
    private static final com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp();
    }

    public static com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoTaskShowResp>
        PARSER = new com.google.protobuf.AbstractParser<VideoTaskShowResp>() {
      public VideoTaskShowResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VideoTaskShowResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VideoTaskShowResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VideoTaskShowResp> getParserForType() {
      return PARSER;
    }

    public com.yy.lite.brpc.service.VideoTaskShow.VideoTaskShowResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030lite/VideoTaskShow.proto\0224com.yy.ent.m" +
      "obile.task.common.domain.lite.shortvideo" +
      "\"8\n\020VideoTaskShowReq\"$\n\004Type\022\010\n\004none\020\000\022\010" +
      "\n\003max\020\3367\022\010\n\003min\020\221\010\"X\n\021VideoTaskShowResp\022" +
      "\014\n\004show\030\001 \001(\005\022\017\n\007skipUrl\030\002 \001(\t\"$\n\004Type\022\010" +
      "\n\004none\020\000\022\010\n\003max\020\3367\022\010\n\003min\020\222\010B\020\242\002\rVideoTa" +
      "skShowb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowReq_descriptor,
        new String[] { });
    internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yy_ent_mobile_task_common_domain_lite_shortvideo_VideoTaskShowResp_descriptor,
        new String[] { "Show", "SkipUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
